name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: 
      name: release
    if: github.repository == 'apollographql/artillery-engine-gcp-pubsub'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Install Node with Mise
        uses: jdx/mise-action@v2

      # Because Mise installs Node, this action mostly just caches node_modules.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Build and Install Dependencies
        run: npm ci

      - name: Create Release Pull Request / NPM Publish
        uses: changesets/action@v1
        with:
          publish: npx @changesets/cli version
          version: npx @changesets/cli publish
